### ISSUE TITLE
Version 1.2.1 Does Not Generate Audio

### ISSUE THREAD

**Issue by dzlandis** [Migushthe2nd/MsEdgeTTS#9]
Hi there,

I recently tried updating this package from version 1.1.4 to the latest version (1.2.1). However, upon making this update, I noticed that when I tried to generate audio, no audio was actually being generated. Are there any changes I am supposed to make to my code that occurred between version 1.1.4 and version 1.2.1? Or does the latest version of the package just not work correctly? I had trouble finding a changelog so I'm not sure what changes were made that may cause the problem I am experiencing. Any help is greatly appreciated.

**Comment by Migushthe2nd** [comment]
Hi! Thanks for the heads up. It seems that if you didn't provide prosody options the request would not go through. That's now fixed in 1.2.2.

As for the chagnelog:
- The API has only been extended, (prosody options) not modified.
- You can use a different http agent (for e.g. proxying).
- The socket should remain open now properly. 
- There's now also a new `close()` method to close the ws connection properly.
